// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ytdlwpfdiqpymyfugcoz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl0ZGx3cGZkaXFweW15ZnVnY296Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5NDkzNDQsImV4cCI6MjA2MDUyNTM0NH0.QDOYIkrTX9QquCEtpahTR8YNDoSuGJb15Ls12Yy-Okk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);